name: Build

on:
  push:
    tags:
      - 'v*'
  workflow_dispatch:  # Добавляем ручной запуск

jobs:
  build-windows:
    runs-on: windows-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install pyinstaller tkcalendar
      - name: Build Windows
        run: |
          pyinstaller --onefile --windowed --hidden-import=tkcalendar --name="LessonCounter-Win" lesson_counter.py
      - uses: actions/upload-artifact@v4
        with:
          name: Windows
          path: dist/LessonCounter-Win.exe

  build-macos:
    runs-on: macos-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install pyinstaller tkcalendar
      - name: Build macOS
        run: |
          pyinstaller --onefile --windowed --hidden-import=tkcalendar --name="LessonCounter-Mac" lesson_counter.py
      - uses: actions/upload-artifact@v4
        with:
          name: macOS
          path: dist/LessonCounter-Mac

  build-linux:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v4
        with:
          python-version: '3.12'
      - name: Install dependencies
        run: |
          pip install pyinstaller tkcalendar
      - name: Build Linux
        run: |
          pyinstaller --onefile --hidden-import=tkcalendar --name="LessonCounter-Linux" lesson_counter.py
      - uses: actions/upload-artifact@v4
        with:
          name: Linux
          path: dist/LessonCounter-Linux
